<?php
/**
 * DOWNLOAD NOW - WooCommerce - Post Meta
 * 
 * Post meta boxes for products.
 * 
 * @version	2.2
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_filter( 'manage_product_posts_columns', 'sodn_product_post_column' );
add_action( 'manage_posts_custom_column', 'somdn_product_columns_content', 10, 2 );

function sodn_product_post_column( $columns ) {
	$columns['somdn_free_downloads'] = '<span class="dashicons dashicons-download" data-tip="Free D/Ls" title="Free D/Ls">Free D/Ls</span>';	
	return $columns;
}

function somdn_product_columns_content( $column_name, $post_id ) {

	$download_count = get_post_meta( $post_id, 'somdn_dlcount', true ) ? get_post_meta( $post_id, 'somdn_dlcount', true ) : 0 ;

	if( $column_name == 'somdn_free_downloads' ) {
		echo $download_count;
	}
	
}

add_filter( 'manage_edit-product_sortable_columns', 'somdn_product_sort_columns' );
function somdn_product_sort_columns( $columns ) {
	$columns['somdn_free_downloads'] = array( 'somdn_dlcount', 1 ); 
	return $columns;
}

add_action( 'pre_get_posts', 'somdn_product_sort_columns_query' );
function somdn_product_sort_columns_query( $query ) {

	if( ! is_admin() )
		return;

	$orderby = $query->get( 'orderby');

	if( 'somdn_dlcount' == $orderby ) {

		$query->set( 'meta_query',
			array(
				'relation' => 'OR',
				array(
					'key' => 'somdn_dlcount',
					'compare' => 'EXISTS',
					'type' => 'NUMERIC'
				),
				array(
				'key' => 'somdn_dlcount',
				'compare' => 'NOT EXISTS',
				)
			)
		);

		//$query->set('meta_key','somdn_dlcount');
		//$query->set('orderby','meta_value');
		//$query->set('orderby', 'meta_value_num');
	}
}

/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function download_now_get_meta( $value ) {
	global $post;

	$field = get_post_meta( $post->ID, $value, true );
	if ( ! empty( $field ) ) {
		return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
	} else {
		return false;
	}
}

function download_now_add_meta_box() {

	add_meta_box(
		'download_now-download-now',
		__( 'Download Now', 'download-now-woocommerce' ),
		'download_now_html',
		'product',
		'side',
		'default'
	);

}
add_action( 'add_meta_boxes', 'download_now_add_meta_box' );

function download_now_html( $post ) {

	wp_nonce_field( '_download_now_nonce', 'download_now_nonce' );

	$productID = $post->ID;

	$genoptions = get_option( 'somdn_gen_settings' );

	$price = get_post_meta( $productID, '_regular_price', true);
	$sale = get_post_meta( $productID, '_sale_price', true);

	$onsaleticked = isset( $genoptions['somdn_include_sale_items'] ) ? $genoptions['somdn_include_sale_items'] : false ;

	$somdn_indy = isset( $genoptions['somdn_indy_items'] ) ? $genoptions['somdn_indy_items'] : false ; ?>

	<p style="font-size: 15px;">

		<?php $download_count = get_post_meta( $post->ID, 'somdn_dlcount', true ) ? get_post_meta( $post->ID, 'somdn_dlcount', true ) : 0 ; ?>

			<span class="dashicons dashicons-download"></span> <strong>Total Downloads: <?php echo $download_count; ?></strong>
		
	</p>
	
	<?php if ( somdn_is_product_free( $price, $sale, $onsaleticked ) && $somdn_indy ) { ?>

		<p>

			<input type="checkbox" name="somdn_included" id="somdn_included" value="somdn_included" <?php echo ( download_now_get_meta( 'somdn_included' ) === 'somdn_included' ) ? 'checked' : ''; ?>>
			<label for="somdn_included"><?php _e( 'Allow download without checkout', 'download-now-woocommerce' ); ?></label>
		</p>
		
		<p class="description">Only applies to free products</p>

	<?php } ?>

	<?php

}

function download_now_save( $post_id ) {
	if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) return;
	if ( ! isset( $_POST['download_now_nonce'] ) || ! wp_verify_nonce( $_POST['download_now_nonce'], '_download_now_nonce' ) ) return;
	if ( ! current_user_can( 'edit_post', $post_id ) ) return;

	if ( isset( $_POST['somdn_included'] ) ) {
		update_post_meta( $post_id, 'somdn_included', esc_attr( $_POST['somdn_included'] ) );
	} else {
		update_post_meta( $post_id, 'somdn_included', null );
	}
}
add_action( 'save_post', 'download_now_save' );

/*
	Usage: download_now_get_meta( 'somdn_included' )
*/
